In [1]:
import sys
from pathlib import Path

DATABASE_DIR = Path("./database").resolve()
sys.path.append(str(DATABASE_DIR))

from db_driver import init_db, create_puzzle, log_step, get_steps_for_puzzle
from utils_board_encoding import board_to_string, string_to_board

print("Database folder:", DATABASE_DIR)
print("Available modules loaded successfully.")


Database folder: /home/tntcastle/_5240/CSC5240-Project/database
Available modules loaded successfully.


In [2]:
# Initialize the database (creates tables if missing)
init_db()
print("Database initialized.")

Database initialized.


In [3]:
#exampl tiny 3x3 board
size = 3
box_rows = 1
box_cols = 3

import numpy as np

tiny_board = np.array([
    [1, 0, 2],
    [0, 0, 3],
    [2, 1, 0]
], dtype=int)

class MockBoard:
    def __init__(self, grid):
        self._grid = grid
        self.size = grid.shape[0]

mock = MockBoard(tiny_board)

# Encode it
initial_str = board_to_string(mock)
print("Encoded board:", initial_str)

Encoded board: 102003210


In [4]:
#insert into db
puzzle_id = create_puzzle(
    size=size,
    box_rows=box_rows,
    box_cols=box_cols,
    initial_board_str=initial_str
)

print("Created puzzle with ID:", puzzle_id)

Created puzzle with ID: 1


In [5]:
#log random steps
#step 1 — filling (row=1, col=2, value=9)
step_1_before = initial_str
step_1_after  = "192003210"   # pretend we filled +1 change
log_step(
    puzzle_id=puzzle_id,
    step_number=1,
    hint_text="Place 9 in row 1, col 2",
    x=2, y=1, value=9,
    board_before=step_1_before,
    board_after=step_1_after,
    method_used="test_method"
)

#step 2 — another fake step
step_2_before = step_1_after
step_2_after  = "192093210"
log_step(
    puzzle_id=puzzle_id,
    step_number=2,
    hint_text="Place 9 in row 2, col 2",
    x=2, y=2, value=9,
    board_before=step_2_before,
    board_after=step_2_after,
    method_used="test_method"
)

print("Logged test steps")

Logged test steps


In [7]:
steps = get_steps_for_puzzle(puzzle_id)

print(f"Found {len(steps)} steps for puzzle {puzzle_id}:\n")

for s in steps:
    print(f"Step #{s['step_number']}")
    print("  Hint:", s['hint_text'])
    print("  Move: (x=", s['x'], ", y=", s['y'], ", value=", s['value'], ")", sep="")
    print("  Before:", s['board_before'])
    print("  After:",  s['board_after'])
    print("  Method:", s['method_used'])
    print("  Timestamp:", s['created_at'])
    print("-" * 40)

Found 2 steps for puzzle 1:

Step #1
  Hint: Place 9 in row 1, col 2
  Move: (x=2, y=1, value=9)
  Before: 102003210
  After: 192003210
  Method: test_method
  Timestamp: 2025-11-17 21:07:33
----------------------------------------
Step #2
  Hint: Place 9 in row 2, col 2
  Move: (x=2, y=2, value=9)
  Before: 192003210
  After: 192093210
  Method: test_method
  Timestamp: 2025-11-17 21:07:33
----------------------------------------


In [8]:
decoded = string_to_board(initial_str, size=size, box_rows=box_rows, box_cols=box_cols)

print("Decoded board matrix:")
print(decoded._grid)

Decoded board matrix:
[[1 0 2]
 [0 0 3]
 [2 1 0]]
